trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
      - release*
  paths:
    exclude:
      - README.md

pr: none

variables:
  repository: 'focal-freedom-236620/kubelet'
  primaryTag: $(Build.SourceBranchName)

jobs:
  - job: Platform
    dependsOn: Kubelet
    pool: server
    variables:
      tag: b-$(buildTag)

    steps:
      - task: InvokeRESTAPI@1
        displayName: 'trigger platform job'
        inputs:
          connectionType: 'connectedServiceName'
          serviceConnection: 'Pipelines'
          method: 'POST'
          urlSuffix: '/edgeworx/_apis/build/builds?api-version=5.0'
          body: "{\"Parameters\":\"{\\\"images.kubelet\\\": \\\"gcr.io/$(repository):$(tag)\\\"}\", \"Definition\":{\"id\":\"5\"}}"
          waitForCompletion: 'false'

  - job: Kubelet
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - script: |
          echo 'setting secondary tag'
          echo "##vso[task.setvariable variable=secondaryTag]b-$(Build.BuildId)"

          if [[ $(Build.SourceBranch) == refs/heads/release* ]]; then
            echo "##vso[task.setvariable variable=primaryTag]rc-$(Build.SourceBranchName)"
          #If branch starts with ref/tags, apply latest and version tag
          elif [[ $(Build.SourceBranch) == refs/tags* ]]; then
            primaryTag= echo $(primaryTag) | awk '{print substr($1,2);}'
            echo $primaryTag
            echo "##vso[task.setvariable variable=primaryTag]$primaryTag"
          fi
        displayName: 'Set Tag variable'
        name: setvarStep

      - task: Docker@2
        displayName: 'docker build and push'
        inputs:
          containerRegistry: 'Edgeworx GCP'
          repository: $(repository)
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile'
          tags: |
            $(primaryTag)
            $(secondaryTag)
            latest
