apiVersion: v1
kind: Pod
metadata:
  name: vkubelet-mock-0
spec:
  containers:
  - name: vkubelet-mock-0
    image: iofog-kubelet
    # "IfNotPresent" is used to prevent Minikube from trying to pull from the registry (and failing) in the first place.
    imagePullPolicy: IfNotPresent
    args:
    - /iofog-kubelet
    - --nodename
    - vkubelet-mock-0
    - --provider
    - mock
    - --provider-config
    - /vkubelet-mock-0-cfg.json
    ports:
    - name: metrics
      containerPort: 10255
    readinessProbe:
      httpGet:
        path: /stats/summary
        port: metrics
  serviceAccountName: iofog-kubelet
